//file path: app/layout.tsx

import type { Metadata } from "next";
import { Big_Shoulders, Inter } from "next/font/google";
import "./globals.css";

import GsapProvider from '@/components/providers/GsapProvider';
import SmoothScroll from "@/components/providers/SmoothScroll";
import RouteChangeRefresh from "@/components/providers/RouteChangeRefresh";
import HashScrollHandler from "@/components/providers/HashScrollHandler";
import IntroSplash from "@/components/transition/IntroSplash";
//import CursorTrail from "@/components/ui/CursorTrail";
import Nav from "@/components/ui/Nav";
import Footer from "@/components/ui/Footer";

// obsidian-intro.html preset [APPLIED]: two typefaces, replacing the prior
// single-typeface (Plus Jakarta Sans) system per Franklin's explicit
// instruction — see CHANGE-NOTES.md.
//
// Big Shoulders Display: condensed display face, used ONLY for the hero
// headline and the intro's percentage counter (weight 300/Light in both,
// matching the reference). Weights 300/400/600 kept available in case a
// heavier cut is wanted later for either spot.
const bigShouldersDisplay = Big_Shoulders({
  subsets: ["latin"],
  weight: "variable",
  axes: ["opsz"],
  variable: "--font-big-shoulders-display",
  display: "swap",
});

// Inter: the workhorse face for everything else — nav, body copy, labels,
// the hero subline, the intro's loading/eyebrow text.
const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Franklin Sarmiento — Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${bigShouldersDisplay.variable} ${inter.variable}`}
    >
      <body>
        <GsapProvider>
          {/* Mounted once per real document load, not per client-side nav —
              see IntroSplash.tsx's module-scope flag for why that's exactly
              the persistence this needs. Fixed/full-bleed, so its position
              in this tree doesn't matter for paint order. */}
          <IntroSplash />
          {/* Mounted once, persists for the whole session. Renders nothing
              visible until IntroSplash's caret hands off to it — see
              CURSOR_HANDOFF_EVENT in IntroSplash.tsx. Replaces the old,
              never-mounted Cursor.tsx (safe to delete that file now).
              
          <CursorTrail />
           */}
          
          <RouteChangeRefresh />
          <HashScrollHandler />
          <SmoothScroll>
            <Nav />
            {children}
            <Footer />
          </SmoothScroll>
        </GsapProvider>
      </body>
    </html>
  );
}